{
    "name": "Invoice Task Detail",
    "version": "1.0",
    "category": "Accounting",
    'author': "Yayan Hidayatulloh",
    'website': "",
    "summary": "Custom task detail & GST on invoice",
    "depends": ["account", "purchase", "project", "sale", "stock"],
    "data": [
        "views/account_move_view.xml",
        "views/purchase_view.xml",
        "views/sales_order.xml",
        "views/delivery_order_view.xml",
        "security/ir.model.access.csv",
        "report/report_tax_invoice.xml",
        "report/report.xml",
        "report/purchase_request.xml",
        "report/sales_order.xml",
        "report/delivery_order.xml",
    ],
    "installable": True,
}
